// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Placeholder type — used only to prove the ts-rs codegen pipeline
 * works end-to-end in Phase 0. Will be replaced by real event types
 * (SessionIdle, ToolCallRequested, ToolCallCompleted) in Phase 1.
 *
 * The `export_to` attribute routes this type (and all future types in
 * this crate) into a single `types.ts` file rather than per-type files.
 * This is the intended distribution artifact for `cue-plugins`.
 */
export type Placeholder = { name: string, };
