// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Represents an opencode session that has gone idle.
 * Emitted by the acuity opencode plugin and consumed by the acuity server.
 */
export type SessionIdle = { session_id: string, project_dir: string, session_title: string | null, };
